name: CodeCov
on:
  push:
    branches: [ master, test_actions ]
  pull_request:
    branches: [ master ]
jobs:
  run_tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      # Installs uv and sets up native dependency caching automatically
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.14"

      # Installs all required packages pinned to your uv.lock
      - name: Install dependencies
        run: uv sync --frozen

      - name: Generate Report
        env:
          # now has creds to run integration tests
          IPUMS_API_KEY: ${{ secrets.IPUMS_API_KEY }}
        run: uv run py.test --runint --cov=ipumspy --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
